version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jobportal
      POSTGRES_PASSWORD: jobportal123
      POSTGRES_DB: jobportal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: